BUILD_DIR := _build
IMAGE_BUILD_DIR := $(BUILD_DIR)/images
FRAME_BUILD_DIR := $(BUILD_DIR)/frames

BUILD_FILES := $(sort $(shell go run . -l))
IMAGE_BUILD_FILES := $(filter $(IMAGE_BUILD_DIR)/%, $(BUILD_FILES))
FRAME_BUILD_FILES := $(filter $(FRAME_BUILD_DIR)/%, $(BUILD_FILES))

build: $(IMAGE_BUILD_FILES) $(FRAME_BUILD_FILES)

INSTALL_DIR := _install
IMAGE_INSTALL_DIR := $(INSTALL_DIR)/images
ASSET_INSTALL_DIR := $(INSTALL_DIR)/svg

IMAGE_INSTALL_FILES := $(subst $(IMAGE_BUILD_DIR), $(IMAGE_INSTALL_DIR), $(IMAGE_BUILD_FILES))
FRAME_INSTALL_FILES := $(subst $(FRAME_BUILD_DIR), $(ASSET_INSTALL_DIR), $(FRAME_BUILD_FILES))
FRAME_INSTALL_DIRS := $(sort $(dir $(FRAME_INSTALL_FILES)))
FACEPLATE_INSTALL_FILES := $(subst $(IMAGE_BUILD_DIR), $(ASSET_INSTALL_DIR), $(IMAGE_BUILD_FILES))

install: $(IMAGE_INSTALL_FILES) $(FRAME_INSTALL_FILES) $(FACEPLATE_INSTALL_FILES)

$(ASSET_INSTALL_DIR) $(IMAGE_INSTALL_DIR) $(FRAME_INSTALL_DIRS):
	mkdir -p $@

$(IMAGE_BUILD_FILES) $(FRAME_BUILD_FILES) &:
	go run . -g

$(IMAGE_INSTALL_FILES): $(IMAGE_INSTALL_DIR)/%: $(IMAGE_BUILD_DIR)/% $(IMAGE_INSTALL_DIR)
	./scripts/install-svg.sh $< $@

$(FRAME_INSTALL_FILES): $(ASSET_INSTALL_DIR)/%: $(FRAME_BUILD_DIR)/% $(FRAME_INSTALL_DIRS)
	./scripts/install-svg.sh $< $@

$(FACEPLATE_INSTALL_FILES): $(ASSET_INSTALL_DIR)/%: $(IMAGE_BUILD_DIR)/%
	./scripts/install-faceplate.sh $< $@

clean:
	rm -rf $(BUILD_DIR)

clobber: clean
	rm -rf $(INSTALL_DIR)

.PHONY: clean clobber
