.DEFAULT_GOAL := build

BUILD_DIR=$(abspath _build)
IMAGE_BUILD_DIR=$(BUILD_DIR)/images
FRAME_BUILD_DIR=$(BUILD_DIR)/frames

BUILD_FILES=$(abspath $(shell go run . -l))
IMAGE_BUILD_FILES=$(filter $(IMAGE_BUILD_DIR)/%, $(BUILD_FILES))
FRAME_BUILD_FILES=$(filter $(FRAME_BUILD_DIR)/%, $(BUILD_FILES))

INSTALL_DIR=$(abspath _install)
IMAGE_INSTALL_DIR=$(INSTALL_DIR)/images
ASSET_INSTALL_DIR=$(INSTALL_DIR)/svg

IMAGE_INSTALL_FILES=$(subst $(IMAGE_BUILD_DIR), $(IMAGE_INSTALL_DIR), $(IMAGE_BUILD_FILES))
FRAME_INSTALL_FILES=$(subst $(FRAME_BUILD_DIR), $(ASSET_INSTALL_DIR), $(FRAME_BUILD_FILES))
FRAME_INSTALL_DIRS=$(sort $(dir $(FRAME_INSTALL_FILES)))
FACEPLATE_INSTALL_FILES=$(subst $(IMAGE_BUILD_DIR), $(ASSET_INSTALL_DIR), $(IMAGE_BUILD_FILES))

$(ASSET_INSTALL_DIR) $(IMAGE_INSTALL_DIR) $(FRAME_INSTALL_DIRS):
	mkdir -p $@

$(IMAGE_INSTALL_DIR)/%:  $(dir $(IMAGE_INSTALL_DIR)/%)

$(IMAGE_INSTALL_DIR)/%: $(IMAGE_BUILD_DIR)/%
	./scripts/install-svg.sh $< $@

$(ASSET_INSTALL_DIR)/%: $(FRAME_BUILD_DIR)/%
	./scripts/install-svg.sh $< $@

$(FACEPLATE_INSTALL_FILES): $(ASSET_INSTALL_DIR)

$(ASSET_INSTALL_DIR)/%: $(IMAGE_BUILD_DIR)/%
	./scripts/install-faceplate.sh $< $@

.PHONY: build
build:
	go run . -g

install: $(IMAGE_INSTALL_FILES) $(FRAME_INSTALL_FILES) $(FACEPLATE_INSTALL_FILES)

clean:
	rm -rf $(BUILD_DIR)

clobber: clean
	rm -rf $(INSTALL_DIR)

.PHONY: clean clobber
